version: "3.5"

networks:
    inception_network:
            name: inception

volumes:
    wordpress:
            name: wordpress
            driver: local
            driver_opts:
                    device: /home/osboxes/data/wordpress
                    o: bind
                    type: none
    mariadb:
            name: mariadb
            driver: local
            driver_opts:
                    device: /home/osboxes/data/mariadb
                    o: bind
                    type: none


services:
    nginx:
            depends_on:
                    - wordpress
            container_name: nginx_debian
            build: ./requirements/nginx
            image: nginx
            ports:
                    - "443:443"
            volumes:
                    - wordpress:/var/www/wordpress
            networks:
                    - inception_network
            restart: always

    mariadb:  
            container_name: mariadb_debian
            build: ./requirements/mariadb
            volumes:
                    - mariadb:/var/lib/mysql
            networks:
                    - inception_network
            image: mariadb
            restart: always
            env_file:
                - .env

    wordpress:
            depends_on:
                    - mariadb
            container_name: wordpress_debian
            build: ./requirements/wordpress
            image: wordpress
            volumes:
                    - wordpress:/var/www/wordpress
            networks:
                    - inception_network
            restart: always
            env_file:
                - .env