version: "3.3"
services:

    # mariadb:
    #     build: "./requirements/mariadb"
    #     container_name: mariadb
    #     restart: always
    #     ports: 
    #         - '3316:3316'
    #     networks: 
    #         - app-connect


    # wordpress:
    #     build: "./requirements/wordpress"
    #     container_name: wordpress
    #     restart: always
    #     ports: 
    #         - '8080:8080'
    #     networks: 
    #         - app-connect
    #     depends_on:
    #         - mariadb

    nginx:
        tty: true
        build: "./requirements/nginx"
        container_name: nginx
        restart: always
        ports: 
            - "443:443"
            - "80:80"
        networks: 
           - app-connect
        # depends_on:
        #     - wordpress

networks: 
    app-connect:
        driver: bridge