FROM debian:buster

ARG MARIADB_USER
ARG MARIADB_PASSWORD
ARG MARIADB_ROOT_PASSWORD

RUN apt-get update
RUN apt-get -y install mariadb-server
RUN echo "CREATE DATABASE wordpress;"
RUN echo "CREATE USER 'MARIADB_USER';"
RUN echo "CREATE DATABASE wordpress;"
RUN echo "CREATE DATABASE wordpress;"
